### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by kerochelo** [haganenoubik/mutro#170]
@haganenoubik 
お疲れ様です。
webアプリのフィードバックをお送りいたしますので、ご確認ください。

### フィードバック
- 右上アイコンわかりにくいかもなので、プルダウンメニューであることがわかるUIにする
- ページネーションのUIにデザインを当てこむ
- タイトルのカラムの長さを長くする（フォームいっぱい入れるとエラー出る）
- 世界観がいいですが使い方ページへの導線をわかりやすいところにおいたほうが良さそう（RELEASEボタンが新規投稿と気付けなさそうなど、初見ではちょっと使い方困るかも）
- ヘッダーメニューは導線が被らないように修正する（MY PLAYLISTがかぶっていたりするので）

こちらの内容をissueなどでタスクに落とし込みましたら、本リリースまでに実装する内容と合わせて、実装スケジュールをこちらのスレッドに教えていただければでございます。
また全体的に完成度は高いので、本リリースまでの機能は「レコメンド機能」あたりを実装できれば大丈夫そうかなと思います。

以上よろしくお願いいたします。

**Comment by haganenoubik** [comment]
@kerochelo 
お疲れ様です！
フィードバックありがとうございます。

>右上アイコンわかりにくいかもなので、プルダウンメニューであることがわかるUIにする
自分でもそのように感じていて、ユーザーからも同様の意見をいただいたので下記のイメージで修正しようと思います。
- 未ログイン時：扉アイコン等でログインであることがわかりやすいようにする
- ログイン後：ハンバーガーボタン

>ページネーションのUIにデザインを当てこむ

スタイリングを後回しにしていたので修正します。

>タイトルのカラムの長さを長くする（フォームいっぱい入れるとエラー出る）

表示レイアウトとの兼ね合いもあるので、フォーム自体を小さくするか検討します。（いずれにしても変更します）

>世界観がいいですが使い方ページへの導線をわかりやすいところにおいたほうが良さそう（RELEASEボタンが新規投稿と気付けなさそうなど、初見ではちょっと使い方困るかも）

ご意見いただいた通りなので、使い方ページ自体のアップデートともに導線も検討し直します。

>ヘッダーメニューは導線が被らないように修正する（MY PLAYLISTがかぶっていたりするので）

複数箇所にリンクが被らないよう修正します。

>本リリースまでの機能は「レコメンド機能」あたりを実装できれば大丈夫そうかなと思います。

ありがとうございます。
Spotifyとの同期機能やプレイリストの共同編集機能は、本リリース以降の課題とし、まずは
- オートコンプリート機能 ※とりあえず候補を表示・クリックして検索できるところまでは実装完了
- レコメンド機能
- Googleログイン
- 独自ドメイン適用
- レスポンシブ等のレイアウト・スタイリング修正諸々
あたりまでを、本リリースの実装内容にしようと考えております。

本リリース予定日：2/4（日）

- 実装スケジュール
https://github.com/users/haganenoubik/projects/16/views/1 内
🔥【本リリース】1/22〜28 
🎉【本リリース】1/29〜2/4

**Comment by kerochelo** [comment]
ナイスです 👍
